#pragma once
/* this file was auto-generated from ./src/modules/flow/timestamp/timestamp.json */
#include <stdbool.h>
#include <stdint.h>
#include <sol-flow.h>


#ifdef __cplusplus
extern "C" {
#endif

#define SOL_FLOW_NODE_TYPE_TIMESTAMP_TIME_DEFINED 1
extern const struct sol_flow_node_type *SOL_FLOW_NODE_TYPE_TIMESTAMP_TIME;

struct sol_flow_node_type_timestamp_time_options {
    struct sol_flow_node_options base;
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_TIME_OPTIONS_API_VERSION (1)
    bool initial_packet; /**< Whether to create an initial packet and send it upon connection to the port OUT or not (wait for packets in the TRIGGER port). (default: True) */
};

#define SOL_FLOW_NODE_TYPE_TIMESTAMP_TIME_OPTIONS_DEFAULTS(...) { \
    .base = { \
        SOL_SET_API_VERSION(.api_version = SOL_FLOW_NODE_OPTIONS_API_VERSION, ) \
        SOL_SET_API_VERSION(.sub_api = SOL_FLOW_NODE_TYPE_TIMESTAMP_TIME_OPTIONS_API_VERSION) \
    }, \
    .initial_packet = true, \
    __VA_ARGS__ \
}
/* Input Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_TIME__IN__TRIGGER (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_TIME__IN_LAST (0)

/* Output Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_TIME__OUT__OUT (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_TIME__OUT_LAST (0)

#define SOL_FLOW_NODE_TYPE_TIMESTAMP_MAKE_TIME_DEFINED 1
extern const struct sol_flow_node_type *SOL_FLOW_NODE_TYPE_TIMESTAMP_MAKE_TIME;

/* Input Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_MAKE_TIME__IN__YEAR (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_MAKE_TIME__IN__MONTH (1)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_MAKE_TIME__IN__MONTH_DAY (2)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_MAKE_TIME__IN__HOUR (3)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_MAKE_TIME__IN__MINUTE (4)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_MAKE_TIME__IN__SECOND (5)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_MAKE_TIME__IN__NANO_SECOND (6)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_MAKE_TIME__IN_LAST (6)

/* Output Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_MAKE_TIME__OUT__OUT (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_MAKE_TIME__OUT_LAST (0)

#define SOL_FLOW_NODE_TYPE_TIMESTAMP_SPLIT_TIME_DEFINED 1
extern const struct sol_flow_node_type *SOL_FLOW_NODE_TYPE_TIMESTAMP_SPLIT_TIME;

/* Input Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_SPLIT_TIME__IN__IN (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_SPLIT_TIME__IN_LAST (0)

/* Output Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_SPLIT_TIME__OUT__YEAR (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_SPLIT_TIME__OUT__MONTH (1)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_SPLIT_TIME__OUT__MONTH_DAY (2)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_SPLIT_TIME__OUT__HOUR (3)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_SPLIT_TIME__OUT__MINUTE (4)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_SPLIT_TIME__OUT__SECOND (5)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_SPLIT_TIME__OUT__NANO_SECOND (6)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_SPLIT_TIME__OUT__WEEK_DAY (7)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_SPLIT_TIME__OUT__YEAR_DAY (8)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_SPLIT_TIME__OUT__DAYLIGHT_SAVING_TIME (9)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_SPLIT_TIME__OUT_LAST (9)

#define SOL_FLOW_NODE_TYPE_TIMESTAMP_EQUAL_DEFINED 1
extern const struct sol_flow_node_type *SOL_FLOW_NODE_TYPE_TIMESTAMP_EQUAL;

/* Input Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_EQUAL__IN__IN (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_EQUAL__IN__IN_0 (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_EQUAL__IN__IN_1 (1)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_EQUAL__IN__IN_LAST (1)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_EQUAL__IN_LAST (1)

/* Output Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_EQUAL__OUT__OUT (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_EQUAL__OUT_LAST (0)

#define SOL_FLOW_NODE_TYPE_TIMESTAMP_GREATER_DEFINED 1
extern const struct sol_flow_node_type *SOL_FLOW_NODE_TYPE_TIMESTAMP_GREATER;

/* Input Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_GREATER__IN__IN (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_GREATER__IN__IN_0 (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_GREATER__IN__IN_1 (1)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_GREATER__IN__IN_LAST (1)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_GREATER__IN_LAST (1)

/* Output Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_GREATER__OUT__OUT (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_GREATER__OUT_LAST (0)

#define SOL_FLOW_NODE_TYPE_TIMESTAMP_GREATER_OR_EQUAL_DEFINED 1
extern const struct sol_flow_node_type *SOL_FLOW_NODE_TYPE_TIMESTAMP_GREATER_OR_EQUAL;

/* Input Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_GREATER_OR_EQUAL__IN__IN (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_GREATER_OR_EQUAL__IN__IN_0 (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_GREATER_OR_EQUAL__IN__IN_1 (1)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_GREATER_OR_EQUAL__IN__IN_LAST (1)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_GREATER_OR_EQUAL__IN_LAST (1)

/* Output Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_GREATER_OR_EQUAL__OUT__OUT (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_GREATER_OR_EQUAL__OUT_LAST (0)

#define SOL_FLOW_NODE_TYPE_TIMESTAMP_LESS_DEFINED 1
extern const struct sol_flow_node_type *SOL_FLOW_NODE_TYPE_TIMESTAMP_LESS;

/* Input Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_LESS__IN__IN (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_LESS__IN__IN_0 (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_LESS__IN__IN_1 (1)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_LESS__IN__IN_LAST (1)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_LESS__IN_LAST (1)

/* Output Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_LESS__OUT__OUT (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_LESS__OUT_LAST (0)

#define SOL_FLOW_NODE_TYPE_TIMESTAMP_LESS_OR_EQUAL_DEFINED 1
extern const struct sol_flow_node_type *SOL_FLOW_NODE_TYPE_TIMESTAMP_LESS_OR_EQUAL;

/* Input Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_LESS_OR_EQUAL__IN__IN (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_LESS_OR_EQUAL__IN__IN_0 (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_LESS_OR_EQUAL__IN__IN_1 (1)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_LESS_OR_EQUAL__IN__IN_LAST (1)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_LESS_OR_EQUAL__IN_LAST (1)

/* Output Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_LESS_OR_EQUAL__OUT__OUT (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_LESS_OR_EQUAL__OUT_LAST (0)

#define SOL_FLOW_NODE_TYPE_TIMESTAMP_NOT_EQUAL_DEFINED 1
extern const struct sol_flow_node_type *SOL_FLOW_NODE_TYPE_TIMESTAMP_NOT_EQUAL;

/* Input Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_NOT_EQUAL__IN__IN (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_NOT_EQUAL__IN__IN_0 (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_NOT_EQUAL__IN__IN_1 (1)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_NOT_EQUAL__IN__IN_LAST (1)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_NOT_EQUAL__IN_LAST (1)

/* Output Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_NOT_EQUAL__OUT__OUT (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_NOT_EQUAL__OUT_LAST (0)

#define SOL_FLOW_NODE_TYPE_TIMESTAMP_DELTA_DEFINED 1
extern const struct sol_flow_node_type *SOL_FLOW_NODE_TYPE_TIMESTAMP_DELTA;

/* Input Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_DELTA__IN__IN (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_DELTA__IN__IN_0 (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_DELTA__IN__IN_1 (1)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_DELTA__IN__IN_LAST (1)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_DELTA__IN_LAST (1)

/* Output Ports */
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_DELTA__OUT__SECONDS (0)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_DELTA__OUT__NANO_SECONDS (1)
#define SOL_FLOW_NODE_TYPE_TIMESTAMP_DELTA__OUT_LAST (1)

#ifndef SOL_LOG_DOMAIN
#define SOL_LOG_DOMAIN &_log_domain
#include "sol-log.h"

#ifdef SOL_LOG_ENABLED
#define SOL_LOG_INTERNAL_DECLARE(_var, _name)     SOL_ATTR_UNUSED struct sol_log_domain _var = {         .name = "sol-" _name,         .color = SOL_LOG_COLOR_MAGENTA,         .level = SOL_LOG_LEVEL_WARNING     }

#define SOL_LOG_INTERNAL_DECLARE_STATIC(_var, _name)     static SOL_LOG_INTERNAL_DECLARE(_var, _name)

SOL_LOG_INTERNAL_DECLARE_STATIC(_log_domain, "flow-timestamp");

#else // #ifdef SOL_LOG_ENABLED

#define SOL_LOG_INTERNAL_DECLARE(_var, _name)
#define SOL_LOG_INTERNAL_DECLARE_STATIC(_var, _name)

#ifdef SOL_LOG_DOMAIN
#undef SOL_LOG_DOMAIN
#define SOL_LOG_DOMAIN NULL
#endif // #ifdef SOL_LOG_DOMAIN

#endif // #ifdef SOL_LOG_ENABLED
#endif // ifndef SOL_LOG_DOMAIN

#ifdef __cplusplus
}
#endif
